apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Values.service.name }}
  annotations:
    kubernetes.io/ingress.global-static-ip-name: "secure-static-ip"
    networking.gke.io/managed-certificates: {{ .Values.environment }}
    kubernetes.io/ingress.class: "gce"
spec:
  rules:
  - host: {{ .Values.domains.frontend }}
    http:
      paths:
      - pathType: ImplementationSpecific
        backend:
          service:
            name: frontend-service
            port:
              number: 80
  - host: {{ .Values.domains.backend }}
    http:
      paths:
      - pathType: ImplementationSpecific
        backend:
          service:
            name: api-gateway
            port:
              number: 80
