apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name }}
  annotations:
    cloud.google.com/backend-config: '{"default": "{{ .Values.deployment.name }}-hc"}'
spec:
  type: {{ .Values.service.type }}
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
  selector:
    app: {{ .Values.deployment.name }}
